version: '3.8'

services:

  mongodb:
    image: mongo:4.4
    container_name: microklimat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microklimat-network

  microklimat:
    build: .
    container_name: microklimat-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/microklimat
    networks:
      - microklimat-network

volumes:
  mongodb_data:

networks:
  microklimat-network:
    driver: bridge
